batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 16
model_path: Models/handwriting_recog/202610071639
train_epochs: 1000
train_workers: 20
vocab: 4PayNFtKVd3ouYJQDez9O:.BlLSmhbIAv0?,sU7wxTM(qE-8WknH)i1Z'5gGjC6";!&c2prR#f
width: 128
